# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """
$time $username@$hostname \
$shlvl\
$hg_branch\
$docker_context\
$cmake\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$conda\
$memory_usage\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$dotnet\
$nodejs\
$package\
$git_branch\
$git_commit\
$git_state\
$git_status\
$status\
\n$directory$character\
"""


# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold green):"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# error_symbol = "[âœ—](bold red):"

[cmd_duration]
min_time = 100
format = "duration [$duration](bold yellow)"
show_notifications=true

[directory]
format="[$path]($style)[$read_only]($read_only_style) "
truncation_length = 8
# truncation_symbol = "â€¦/"
truncate_to_repo=true

[docker_context]
# disabled=true
format = "\\[Docker [ğŸ‹ $context](blue bold)\\]"

[dotnet]
disabled=false
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[git_branch]
# symbol = "ğŸŒ± "
always_show_remote=true
format="[$symbol$branch]($style) "

[git_commit]
disabled=false
commit_hash_length = 8
tag_symbol = "ğŸ”– "

[git_state]
disabled=false
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸğŸ’¨ "
behind = "ğŸ˜° "
diverged = "ğŸ˜µ "
untracked = "ğŸ¤·â€ "
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = '[++\($count\)](green)'
renamed = "ğŸ‘… "
deleted = "ğŸ—‘ "

[memory_usage]
disabled=false
threshold=-1
# symbol=" "
style="bold dimmed green"

[nodejs]
format = "\\[NodeJS [ğŸ¤– $version](bold green)\\] "

# Disable the package module, hiding it from the prompt completely
[package]
disabled=true
display_private=true
format = "[ğŸ $version](208 bold) "

[shlvl]
disabled=false
format="$shlvl level(s) down:"
threshold = 3

[status]
disabled=false
style="bg:blue"
symbol="ğŸ’£ "
format='[\[$symbol$status\]]($style)'

[time]
disabled = false
format = 'ğŸ•™ [\[ $time \]]($style)'
time_format = "%T"
# utc_time_offset = "-5"
# time_range = "10:00:00-18:00:00"

[hostname]
ssh_only = false
format =  "[$hostname](bold red)"
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true